 module.exports.config = {
  name: "nude",
  version: "1.0.0",
  hasPermssion: 2,
  credits: "HungCho",
  description: "Random ảnh nude",
  commandCategory: "random-img",
  usages: "nude",
  cooldowns: 5,
  dependencies: {
    "request":"",
    "fs-extra":"",
    "axios":""
  }
    
};

module.exports.run = async({api,event,args,Users,Threads,Currencies}) => {
const axios = global.nodemodule["axios"];
const request = global.nodemodule["request"];
const fs = global.nodemodule["fs-extra"];
	var link = [
"https://i.imgur.com/MQmWYlg.jpg",
"https://i.imgur.com/aFihSMJ.jpg",
"https://i.imgur.com/vKk3Upu.jpg",
"https://i.imgur.com/pTW9dke.jpg",
"https://i.imgur.com/NJ2nM8R.jpg",
"https://i.imgur.com/FG2VmeN.jpg",
"https://i.imgur.com/p52xMOx.jpg",
"https://i.imgur.com/hwrAiNJ.jpg",
"https://i.imgur.com/XHVTkO0.jpg",
"https://i.imgur.com/0BZhRh9.jpg",
"https://i.imgur.com/Ejoeciw.jpg",
"https://i.imgur.com/vmaw82S.jpg",
"https://i.imgur.com/1v5mBix.jpg",
"https://i.imgur.com/bhA8Cea.jpg",
"https://i.imgur.com/8o82Jlz.jpg",
"https://i.imgur.com/qUUxLsX.jpg",
"https://i.imgur.com/ApeWTE3.jpg",
"https://i.imgur.com/cJizoU3.jpg",
"https://i.imgur.com/meyyKOj.jpg",
"https://i.imgur.com/67RloK2.jpg",
"https://i.imgur.com/k0DQD1U.jpg",
"https://i.imgur.com/kCGD4X2.jpg",
"https://i.imgur.com/mFa1ssF.jpg",
"https://i.imgur.com/XkQdPaA.jpg",
"https://i.imgur.com/FTliiTV.jpg",
"https://i.imgur.com/B8upcx0.jpg",
"https://i.imgur.com/BJlyP2U.jpg",
"https://i.imgur.com/rzqrDy7.jpg",
"https://i.imgur.com/0vMHfIE.jpg",
"https://i.imgur.com/nCIB9jQ.jpg",
"https://i.imgur.com/9SMrZnx.jpg",
"https://i.imgur.com/6xf5XVU.jpg",
"https://i.imgur.com/ow0pQad.jpg",
"https://i.imgur.com/rg2zLVf.jpg",
"https://i.imgur.com/dnM1ClW.jpg",
"https://i.imgur.com/HGZR8Nr.jpg",
"https://i.imgur.com/Xhodrhf.jpg",
"https://i.imgur.com/uH3vxBL.jpg",
"https://i.imgur.com/cnuD4QO.jpg",
"https://i.imgur.com/S8lYTz6.jpg",
"https://i.imgur.com/bKwhhXg.jpg",
"https://i.imgur.com/OIrBx7S.jpg",
"https://i.imgur.com/aA6iNio.jpg",
"https://i.imgur.com/DQBAb0X.jpg",
"https://i.imgur.com/k1O1MzW.jpg",
"https://i.imgur.com/LCUC0o0.jpg",
"https://i.imgur.com/sjArLJz.jpg",
"https://i.imgur.com/MDbriKB.jpg",
"https://i.imgur.com/YuOWXBJ.jpg",
"https://i.imgur.com/y8zHOcI.jpg",
"https://i.imgur.com/jG1VMXI.jpg",
"https://i.imgur.com/9qLfX0Q.jpg",
"https://i.imgur.com/kBRdvJx.jpg",
"https://i.imgur.com/930TZTM.jpg",
"https://i.imgur.com/vvYA4l9.jpg",
"https://i.imgur.com/pUG7vHa.jpg",
"https://i.imgur.com/2Zg4BbI.jpg",
"https://i.imgur.com/bK6E896.jpg",
"https://i.imgur.com/eYBvwH2.jpg",
"https://i.imgur.com/JofRDwd.jpg",
"https://i.imgur.com/ONNtkKz.jpg",
"https://i.imgur.com/rXyDYPy.jpg",
"https://i.imgur.com/hxVWMiT.jpg",
"https://i.imgur.com/CbYOjB5.jpg",
"https://i.imgur.com/t68UlQ8.jpg",
"https://i.imgur.com/YUZd4kd.jpg",
"https://i.imgur.com/i2xKnsc.jpg",
"https://i.imgur.com/xp6DWEV.jpg",
"https://i.imgur.com/t7QRBbg.jpg",
"https://i.imgur.com/02tzm6v.jpg",
"https://i.imgur.com/3hpJ02X.jpg",
"https://i.imgur.com/T1FyF2e.jpg",
"https://i.imgur.com/tMSjSz0.jpg",
"https://i.imgur.com/CWXXa7k.jpg",
"https://i.imgur.com/ph5WGb6.jpg",
"https://i.imgur.com/16iE2MP.jpg",
"https://i.imgur.com/1HIym0d.jpg",
"https://i.imgur.com/W0ZrbWD.jpg",
"https://i.imgur.com/j5wghyC.jpg",
"https://i.imgur.com/rQ8Vij4.jpg",
"https://i.imgur.com/WYEni8m.jpg",
"https://i.imgur.com/GRW6gDU.jpg",
"https://i.imgur.com/VTcYubR.jpg",
"https://i.imgur.com/jp58AAN.jpg",
"https://i.imgur.com/IIQSc1w.jpg",
];
	 var callback = () => api.sendMessage({body:`Ảnh Nude Random \nSố ảnh: ${link.length}`,attachment: fs.createReadStream(__dirname + "/cache/1.jpg")}, event.threadID, () => fs.unlinkSync(__dirname + "/cache/1.jpg"));	
      return request(encodeURI(link[Math.floor(Math.random() * link.length)])).pipe(fs.createWriteStream(__dirname+"/cache/1.jpg")).on("close",() => callback());
   };